/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Aluno;

/**
 *
 * @author Bruno Rodrigues(11211501661@alunos.umc.br)
 * @author Bianca Gomes(11211101607@alunos.umc.br)
 */
public class Dados extends javax.swing.JFrame {

    /**
     * Creates new form Dados
     */
    public Dados() {
        initComponents();
        
    }

    public void exibir(Aluno a) {
        jlbl_nome_dado.setText(a.getNome());
        jlbl_sobrenome_dado.setText(a.getSobrenome());
        jlbl_nasc_dado.setText(a.getNasc());
        jlbl_rgm_dado.setText(a.getRgm());
        jlbl_genero_dado.setText(a.getSexo());
        jlbl_curso_dado.setText(a.getCurso());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl_nome = new javax.swing.JLabel();
        jlbl_nome_dado = new javax.swing.JLabel();
        jlbl_nasc = new javax.swing.JLabel();
        jlbl_nasc_dado = new javax.swing.JLabel();
        jlbl_rgm = new javax.swing.JLabel();
        jlbl_rgm_dado = new javax.swing.JLabel();
        jlbl_sobrenome = new javax.swing.JLabel();
        jlbl_sobrenome_dado = new javax.swing.JLabel();
        jlbl_genero = new javax.swing.JLabel();
        jlbl_genero_dado = new javax.swing.JLabel();
        jlbl_curso = new javax.swing.JLabel();
        jlbl_curso_dado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbl_nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbl_nome.setText("Nome");

        jlbl_nome_dado.setText("jLabel2");

        jlbl_nasc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbl_nasc.setText("Data de Nascimento");

        jlbl_nasc_dado.setText("jLabel4");

        jlbl_rgm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbl_rgm.setText("RGM");

        jlbl_rgm_dado.setText("jLabel6");

        jlbl_sobrenome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbl_sobrenome.setText("Sobrenome");

        jlbl_sobrenome_dado.setText("jLabel8");

        jlbl_genero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbl_genero.setText("Gênero");

        jlbl_genero_dado.setText("jLabel10");

        jlbl_curso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbl_curso.setText("Curso");

        jlbl_curso_dado.setText("jLabel12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_nome)
                    .addComponent(jlbl_nome_dado)
                    .addComponent(jlbl_nasc)
                    .addComponent(jlbl_nasc_dado)
                    .addComponent(jlbl_rgm)
                    .addComponent(jlbl_rgm_dado))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_curso_dado)
                    .addComponent(jlbl_curso)
                    .addComponent(jlbl_genero_dado)
                    .addComponent(jlbl_genero)
                    .addComponent(jlbl_sobrenome_dado)
                    .addComponent(jlbl_sobrenome))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_nome)
                    .addComponent(jlbl_sobrenome))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_nome_dado)
                    .addComponent(jlbl_sobrenome_dado))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_nasc)
                    .addComponent(jlbl_genero))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_nasc_dado)
                    .addComponent(jlbl_genero_dado))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_rgm)
                    .addComponent(jlbl_curso))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_rgm_dado)
                    .addComponent(jlbl_curso_dado))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbl_curso;
    private javax.swing.JLabel jlbl_curso_dado;
    private javax.swing.JLabel jlbl_genero;
    private javax.swing.JLabel jlbl_genero_dado;
    private javax.swing.JLabel jlbl_nasc;
    private javax.swing.JLabel jlbl_nasc_dado;
    private javax.swing.JLabel jlbl_nome;
    private javax.swing.JLabel jlbl_nome_dado;
    private javax.swing.JLabel jlbl_rgm;
    private javax.swing.JLabel jlbl_rgm_dado;
    private javax.swing.JLabel jlbl_sobrenome;
    private javax.swing.JLabel jlbl_sobrenome_dado;
    // End of variables declaration//GEN-END:variables
}
