/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.Aluno;

/**
 *
 * @Guilherme Antunes RGM : 11211102142 Eduarda Shibakura RGM :112111102084
 */
public class Formulario extends javax.swing.JFrame {

    //Instanciar Aluno e Jframe Dados
    Aluno a = new Aluno();
    Dados dados = new Dados();

    /**
     * Creates new form JFrame
     */
    public Formulario() {
        initComponents();
        jRadioButton_sexo_masc.setActionCommand("Masculino");
        jRadioButton_sexo_fem.setActionCommand("Feminino");
        buttonGroup1.add(jRadioButton_sexo_masc);
        buttonGroup1.add(jRadioButton_sexo_fem);
        jRadioButton_sexo_masc.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jlbl_nome = new javax.swing.JLabel();
        jTextF_nome = new javax.swing.JTextField();
        jlbl_sobrenome = new javax.swing.JLabel();
        jTextF_sobrenome = new javax.swing.JTextField();
        jLabel_nasc = new javax.swing.JLabel();
        jFormTextF_nasc = new javax.swing.JFormattedTextField();
        jlbl_rgm = new javax.swing.JLabel();
        jTextF_rgm = new javax.swing.JTextField();
        jlbl_sexo = new javax.swing.JLabel();
        jRadioButton_sexo_masc = new javax.swing.JRadioButton();
        jRadioButton_sexo_fem = new javax.swing.JRadioButton();
        jLabel_curso = new javax.swing.JLabel();
        jComboBox_curso = new javax.swing.JComboBox<>();
        btn_atualizar = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbl_nome.setText("Nome");

        jTextF_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextF_nomeActionPerformed(evt);
            }
        });

        jlbl_sobrenome.setText("Sobrenome");

        jLabel_nasc.setText("Data de Nascimento");

        try {
            jFormTextF_nasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormTextF_nasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormTextF_nascActionPerformed(evt);
            }
        });

        jlbl_rgm.setText("RGM");

        jTextF_rgm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextF_rgmActionPerformed(evt);
            }
        });

        jlbl_sexo.setText("Sexo");

        jRadioButton_sexo_masc.setText("Masculino");
        jRadioButton_sexo_masc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_sexo_mascActionPerformed(evt);
            }
        });

        jRadioButton_sexo_fem.setText("Feminino");
        jRadioButton_sexo_fem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_sexo_femActionPerformed(evt);
            }
        });

        jLabel_curso.setText("Curso");

        jComboBox_curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistemas de Informação", "Análise e Desenvolvimento de Sistemas", "Engenharia de Software", "Segurança de Informação", "Gestão e Tecnologia da Informação", "Banco de Dados", "Desenvolvimento de Software em Sistemas multiplataforma" }));
        jComboBox_curso.setToolTipText("");
        jComboBox_curso.setBorder(null);
        jComboBox_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_cursoActionPerformed(evt);
            }
        });

        btn_atualizar.setText("Atualizar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextF_rgm)
                            .addComponent(jlbl_rgm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFormTextF_nasc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextF_nome)
                            .addComponent(jLabel_nasc, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbl_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton_sexo_masc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton_sexo_fem))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextF_sobrenome)
                                        .addComponent(jlbl_sobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(jlbl_sexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 100, Short.MAX_VALUE))
                            .addComponent(jLabel_curso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox_curso, 0, 249, Short.MAX_VALUE)
                        .addGap(21, 21, 21))))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btn_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_nome)
                    .addComponent(jlbl_sobrenome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextF_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nasc)
                    .addComponent(jlbl_sexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormTextF_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_sexo_masc)
                    .addComponent(jRadioButton_sexo_fem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_curso)
                    .addComponent(jlbl_rgm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextF_rgm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btn_atualizar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextF_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextF_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextF_nomeActionPerformed

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "Você deseja atualizar", "Atualizar", JOptionPane.YES_NO_OPTION);

        if (n == 0) {
            a.setNome(jTextF_nome.getText());
            a.setSobrenome(jTextF_sobrenome.getText());
            a.setNasc(jFormTextF_nasc.getText());
            a.setRgm(jTextF_rgm.getText());
            a.setNasc(jFormTextF_nasc.getText());
            a.setSexo(buttonGroup1.getSelection().getActionCommand());
            int cb = jComboBox_curso.getSelectedIndex();
            a.setCurso(jComboBox_curso.getItemAt(cb));
            btn_atualizar.setText("Atualizado");

        } else {
            btn_atualizar.setText("Não atualizado");
        }

        dados.exibir(a);
        dados.setVisible(true);
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void jFormTextF_nascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormTextF_nascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormTextF_nascActionPerformed

    private void jTextF_rgmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextF_rgmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextF_rgmActionPerformed

    private void jComboBox_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_cursoActionPerformed

    private void jRadioButton_sexo_mascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_sexo_mascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_sexo_mascActionPerformed

    private void jRadioButton_sexo_femActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_sexo_femActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_sexo_femActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualizar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox_curso;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFormattedTextField jFormTextF_nasc;
    private javax.swing.JLabel jLabel_curso;
    private javax.swing.JLabel jLabel_nasc;
    private javax.swing.JRadioButton jRadioButton_sexo_fem;
    private javax.swing.JRadioButton jRadioButton_sexo_masc;
    private javax.swing.JTextField jTextF_nome;
    private javax.swing.JTextField jTextF_rgm;
    private javax.swing.JTextField jTextF_sobrenome;
    private javax.swing.JLabel jlbl_nome;
    private javax.swing.JLabel jlbl_rgm;
    private javax.swing.JLabel jlbl_sexo;
    private javax.swing.JLabel jlbl_sobrenome;
    // End of variables declaration//GEN-END:variables
}
